import './globals.css'
import type { Metadata } from 'next'
import {Poppins } from 'next/font/google'
import localFont from 'next/font/local'



const octarine = localFont({
  variable: '--font-octarine-bold',
  src: [
    {
      path: './Octarine-Bold.otf',
    },
   
  ],
})
 
const poppinsLight = localFont({
  variable: '--font-poppins-light',
  src: [
    {
      path: './Poppins-Light.ttf',
    },
   
  ],
});

const poppinsMedium = localFont({
  variable: '--font-poppins-medium',
  src: [
    {
      path: './Poppins-Medium.ttf',
    },
   
  ],
});
const poppinsBold = localFont({
  variable: '--font-poppins-bold',
  src: [
    {
      path: './Poppins-Bold.ttf',
    },
   
  ],
});

const poppinsRegular = localFont({
  variable: '--font-poppins-regular',
  src: [
    {
      path: './Poppins-Regular.ttf',
    },
   
  ],
});


const poppinsSemiBold = localFont({
  variable: '--font-poppins-semibold',
  src: [
    {
      path: './Poppins-SemiBold.ttf',
    },
   
  ],
});



 


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr" className={` ${poppinsLight.variable} ${poppinsSemiBold.variable} ${poppinsRegular.variable} ${octarine.variable} ${poppinsMedium.variable} ${poppinsBold.variable}`}>
      <body>{children}</body>
    </html>
  )
}
